sources:
  openstack:
    source: ssh://centos@10.0.0.1/./.kube/config
    insecure: true
    apiaddress: https://10.100.0.1:6443
  vagrant:
    source: ssh://vagrant@192.168.0.1:2222/./.kube/config
  local:
    source: ~/projects/kuberetes/example.com/config
destination: ~/.kube/config
defaultsourcepath: ~/.kube/config
